"""create initial tables

Revision ID: 774d228dcd30
Revises: 
Create Date: 2026-09-17 23:08:46.736344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774d228dcd30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('nm_produto', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setor',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('nm_setor', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subsetor',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id_setor', sa.BigInteger(), nullable=False),
    sa.Column('nm_subsetor', sa.String(length=255), nullable=False),
    sa.Column('id_produto', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['id_setor'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('nm_usuario', sa.String(length=100), nullable=False),
    sa.Column('id_subsetor', sa.BigInteger(), nullable=False),
    sa.Column('cargo', sa.Enum('ADMIN', 'GERENTE', 'ANALISTA', name='cargo_usuario'), nullable=False),
    sa.Column('id_produto', sa.BigInteger(), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('nm_completo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['id_subsetor'], ['subsetor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nm_usuario')
    )
    op.create_table('cliente',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('nm_cliente', sa.String(length=255), nullable=False),
    sa.Column('id_setor_atendimento', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_setor_atendimento'], ['setor.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correcao',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ticket', sa.String(length=100), nullable=False),
    sa.Column('ticket_bug', sa.String(length=100), nullable=True),
    sa.Column('merge', sa.String(length=255), nullable=True),
    sa.Column('id_cliente', sa.BigInteger(), nullable=False),
    sa.Column('id_produto', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('id_setor', sa.BigInteger(), nullable=False),
    sa.Column('sn_mergeado', sa.CHAR(length=1), nullable=True),
    sa.Column('versao_correcao', sa.String(length=50), nullable=False),
    sa.Column('sn_aprovado_code_review', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['id_setor'], ['setor.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacote',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id_correcao', sa.BigInteger(), nullable=False),
    sa.Column('sn_aplicado', sa.CHAR(length=1), nullable=False),
    sa.Column('tp_pacote', sa.BigInteger(), nullable=False),
    sa.Column('nm_pacote', sa.String(length=255), nullable=False),
    sa.Column('sn_aprovado_usu', sa.CHAR(length=1), nullable=True),
    sa.Column('sn_aprovado_gerente', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['id_correcao'], ['correcao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacote')
    op.drop_table('correcao')
    op.drop_table('cliente')
    op.drop_table('usuario')
    op.drop_table('subsetor')
    op.drop_table('setor')
    op.drop_table('produto')
    # ### end Alembic commands ###
